/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "RCC.h"
#include "DAC.h"
#include "Pwr.h"
#include "GPIO.h"
#include "BasicTIM.h"
#include "MelodyPlayer.h"
#include "Melodies.h"
#include "SineGen.h"
#include "Utilities.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

static uint32 SysTick;

void SysTick_Inc(void)
{
    SysTick++;
}

uint32 GetTicks(void)
{
    return SysTick;
}

int main(void)
{
    asm("LDR.W   R0, =0xE000ED88");
    asm("LDR     R1, [R0]");
    asm("ORR     R1, R1, #(0xF << 20)");
    asm("STR     R1, [R0]");
    RCC_ClockEnable(RCC_GPIOA, Enable);
    RCC_ClockEnable(RCC_GPIOB, Enable);
    RCC_ClockEnable(RCC_GPIOC, Enable);
    RCC_ClockEnable(RCC_PWR, Enable);
    RCC_ClockEnable(RCC_FLASH, Enable);
    RCC_ClockEnable(RCC_TIM7, Enable);
    RCC_ClockEnable(RCC_TIM6, Enable);
    RCC_ClockEnable(RCC_DMA1, Enable);
    RCC_ClockEnable(RCC_DAC, Enable);

    uint32 Timestamp = GetTicks();
    uint8 ButtonCntr = 0;


    dtRccInitConfig RCCConf = {.Clock = 80000000, .AHB_Presc = AHB_Presc1, .APB1_Presc = APB_Presc1, .CrystalOrInternal = Internal, .PLL_QDiv = QDiv_4};
    dtDACConf Config = {.Channel = Dac_Channel1, .Mode = 0, .Trigger = Dac_Trigger_Disabled, .Wave = Dac_Wave_Disabled};
    dtBasicTimConfig config = {.MasterMode = 0, .AutoReload = 800, .Prescaler = 99, .ARPreload = 1, .UpdateDisable = 0, .UpdateSource = 0, .OnePulse = 0, .Enable = 1};
    dtGPIOConfig LedConfig = {.Type = PushPull, .Speed  = VeryHigh, .PUPD = NoPull, .Mode = Output};
    dtGPIOConfig ButtonConfig = {.Type = PushPull, .Speed  = Medium, .PUPD = NoPull, .Mode = Input};
    RCC_ClockSet(RCCConf);

    GPIO_PinInit(PortB_13, LedConfig);
    GPIO_PinInit(PortC_13, ButtonConfig);
    GPIO_PinInit(PortA_0, LedConfig);
    GPIO_PinInit(PortA_1, LedConfig);

    BasicTIM_Set(TIM7, config, SysTick_Inc);

    DAC_Init(Config);
    SineGen_Init();

    dtMelody StarWarsMelody = {.Length = sizeof(StarWarsMainTheme)/sizeof(dtMusicNoteDesc), .beat = 108, .Notes = StarWarsMainTheme};
    dtMelody CoffinDanceMelody = {.Length = sizeof(CoffinDance)/sizeof(dtMusicNoteDesc), .beat = 127, .Notes = CoffinDance};


    /* Loop forever */
	for(;;)
	{
	    MelodyPlayer_Task();
	    if((GPIO_Get(PortC_13) == 0) && IsPassed(Timestamp, 300))
	    {
	        Timestamp = GetTicks();
	        ButtonCntr++;
	        switch(ButtonCntr)
	        {
	            case 1:
	                MelodyPlayer_Start(CoffinDanceMelody);
	                break;
	            case 2:
                    MelodyPlayer_Stop();
	                MelodyPlayer_Start(StarWarsMelody);
	                break;
	            default:
                    MelodyPlayer_Stop();
	                ButtonCntr = 0;
	        }
	    }
	}
}

